version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    image: php:7.1.8-apache
    ports:
      - 8180:80
    volumes:
      - ./app:/var/www/html
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: toshdb
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: toshdb
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password